In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.cluster import (
    KMeans,
    MiniBatchKMeans,
    AgglomerativeClustering,
    SpectralClustering,
    DBSCAN
)

from sklearn.mixture import GaussianMixture
from sklearn.metrics import (
    silhouette_score,
    calinski_harabasz_score,
    davies_bouldin_score
)

sns.set_style("whitegrid")

In [2]:
df = pd.read_csv("../outputs/soil_features_scaled.csv")
df.head()

,taw,organic_carbon,cec,ph,sand_pct,lat,lon,texture_class
0,1.474726,-1.910414,0.164547,2.368321,1.222510,7.323213,80.125184,Loamy sand
1,1.605418,-1.924883,0.163914,2.370244,1.206451,7.323213,80.134612,Loamy sand
2,-0.594931,-1.328773,0.143537,2.250122,1.658271,7.313786,80.002622,Loamy sand
3,-0.515371,-1.336697,0.143093,2.237952,1.621037,7.313786,80.012050,Loamy sand
4,-0.434370,-1.344749,0.142641,2.227331,1.585134,7.313786,80.021478,Loamy sand

In [3]:
CLUSTER_FEATURES = [
    "taw",
    "organic_carbon",
    "cec",
    "ph",
    "sand_pct"
]

X = df[CLUSTER_FEATURES].values
print("Feature matrix shape:", X.shape)

Feature matrix shape: (3422, 5)

In [4]:
def evaluate_clustering(X, labels):
    return {
        "silhouette": silhouette_score(X, labels),
        "calinski_harabasz": calinski_harabasz_score(X, labels),
        "davies_bouldin": davies_bouldin_score(X, labels)
    }

In [5]:
kmeans_results = []

for k in range(2, 9):
    model = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )
    labels = model.fit_predict(X)
    metrics = evaluate_clustering(X, labels)

    kmeans_results.append({
        "model": "KMeans",
        "k": k,
        **metrics
    })

kmeans_df = pd.DataFrame(kmeans_results)
kmeans_df

    model  k  silhouette  calinski_harabasz  davies_bouldin
0  KMeans  2    0.376670        1934.772838        1.152724
1  KMeans  3    0.470120        2602.868202        0.910918
2  KMeans  4    0.510569        2796.242839        0.722892
3  KMeans  5    0.462284        2765.675062        0.765861
4  KMeans  6    0.426108        2863.890241        0.853004
5  KMeans  7    0.417926        2912.353260        0.863344
6  KMeans  8    0.415294        2805.962733        0.853221